# TEST_CLASSIFICATION: SPECIFIED
"""Unit tests for the Greedy Agent.

Contract under test (documents/agent/greedy-agent.md):
  - Given the same state, the agent produces the same action (determinism)
  - Agent prefers pawn moves that decrease own shortest path length (moves toward goal)
  - Agent considers wall placements generated by local engine
  - Stateless: repeated make_action calls on the same input produce the same result
  - Direction: agent moves toward opponent's goal, not sideways
"""

from __future__ import annotations

import pytest

from agent_system.runtime.service.agents.greedy_agent import GreedyAgent

# ---------------------------------------------------------------------------
# Shared test fixtures
# ---------------------------------------------------------------------------

# Initial game state — no walls, standard starting positions.
# P1 at (x=4, y=0), P2 at (x=4, y=8) in engine coords.
# Wire format: row=x, col=y.
_INITIAL_STATE = {
    "current_player": 1,
    "pawns": {
        "1": {"row": 4, "col": 0},
        "2": {"row": 4, "col": 8},
    },
    "walls_remaining": {"1": 10, "2": 10},
    "wall_state": {
        "horizontal_edges": 0,
        "vertical_edges": 0,
        "horizontal_heads": 0,
        "vertical_heads": 0,
    },
    "game_over": False,
    "winner": None,
}

# Legal pawn actions for P1 from start: left, forward, right.
# Forward move (row=4, col=1) advances P1 toward goal (col=8).
_P1_LEGAL_ACTIONS = [
    {"player": 1, "type": "pawn", "target": [3, 0]},  # left
    {"player": 1, "type": "pawn", "target": [4, 1]},  # forward (toward goal)
    {"player": 1, "type": "pawn", "target": [5, 0]},  # right
]

_FORWARD_ACTION = {"player": 1, "type": "pawn", "target": [4, 1]}


# State where P2 is 1 step from goal at edge corner.
# Horizontal wall at (0,0) blocks P2's direct path, scoring +2 vs best pawn +1.
_WALL_ADVANTAGE_STATE = {
    "current_player": 1,
    "pawns": {
        "1": {"row": 4, "col": 4},
        "2": {"row": 0, "col": 1},
    },
    "walls_remaining": {"1": 10, "2": 10},
    "wall_state": {
        "horizontal_edges": 0,
        "vertical_edges": 0,
        "horizontal_heads": 0,
        "vertical_heads": 0,
    },
    "game_over": False,
    "winner": None,
}

# Pawn-only legal actions for P1 from (4,4): four directions.
_WALL_ADVANTAGE_LEGAL = [
    {"player": 1, "type": "pawn", "target": [3, 4]},
    {"player": 1, "type": "pawn", "target": [5, 4]},
    {"player": 1, "type": "pawn", "target": [4, 5]},
    {"player": 1, "type": "pawn", "target": [4, 3]},
]


# ---------------------------------------------------------------------------
# Test: direction — must move toward goal, not sideways
# ---------------------------------------------------------------------------

def test_direction_toward_goal():
    """On the initial board, chosen action must advance P1 toward goal (increasing col)."""
    agent = GreedyAgent()
    result = agent.make_action(_INITIAL_STATE, _P1_LEGAL_ACTIONS)
    # P1 starts at col=0, goal is col=8 — forward means col increases.
    assert result["target"][1] > 0, "P1 must move toward goal (increasing col), not sideways"
    # Must not move laterally (same col=0).
    assert result == _FORWARD_ACTION


# ---------------------------------------------------------------------------
# Test: determinism — same inputs produce same output
# ---------------------------------------------------------------------------

def test_deterministic_same_state():
    """Given the same state, the agent always returns the same action."""
    agent = GreedyAgent()
    first = agent.make_action(_INITIAL_STATE, _P1_LEGAL_ACTIONS)
    second = agent.make_action(_INITIAL_STATE, _P1_LEGAL_ACTIONS)
    assert first == second


# ---------------------------------------------------------------------------
# Test: evaluation sanity — forward move scores highest on empty board
# ---------------------------------------------------------------------------

def test_evaluation_prefers_forward_move():
    """On the initial board, the forward pawn move has the best score and must be selected.

    From the initial position:
      forward (4,1): delta_my = -1, delta_opp = 0 → score = 1
      sideways (3,0) or (5,0): delta_my = 0, delta_opp = 0 → score = 0
      all walls: score = 0 (symmetric board)
    """
    agent = GreedyAgent()
    result = agent.make_action(_INITIAL_STATE, _P1_LEGAL_ACTIONS)
    assert result == _FORWARD_ACTION


# ---------------------------------------------------------------------------
# Test: wall consideration — greedy places wall when clearly beneficial
# ---------------------------------------------------------------------------

def test_wall_consideration():
    """When P2 is near goal at edge, a blocking wall scores higher than any pawn move.

    P1 at (4,4) path=4, P2 at (0,1) path=1.
    Best pawn move (4,5): score = 1 (delta_my=-1, delta_opp=0).
    Horizontal wall at (0,0): score = 2 (delta_opp=+2, delta_my=0).
    Greedy must select a wall action.
    """
    agent = GreedyAgent()
    result = agent.make_action(_WALL_ADVANTAGE_STATE, _WALL_ADVANTAGE_LEGAL)
    assert result["type"] in ("horizontal", "vertical"), (
        f"Expected wall action when wall clearly advantageous, got {result['type']}"
    )


# ---------------------------------------------------------------------------
# Test: retry compatibility / stateless — repeated calls do not mutate state
# ---------------------------------------------------------------------------

def test_stateless_repeated_calls():
    """make_action must be safe to call multiple times; output must not change."""
    agent = GreedyAgent()
    results = [agent.make_action(_INITIAL_STATE, _P1_LEGAL_ACTIONS) for _ in range(5)]
    assert all(r == results[0] for r in results)
